### ISSUE TITLE
login not working anymore since ROS 6.45.1

### ISSUE THREAD

**Issue by prnzngr** [vshn/tikapy#12]
I used this libary with 6.43 and it was fine but today I upgraded to 6.45 and it is not working anymore.:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tikapy/__init__.py", line 165, in login
    self._api.login(user, password)
  File "/usr/local/lib/python3.5/dist-packages/tikapy/api/__init__.py", line 85, in login
    "=response=%s" % response])
  File "/usr/local/lib/python3.5/dist-packages/tikapy/api/__init__.py", line 138, in talk
    raise ApiError(replies[0][1])
tikapy.api.ApiError: {'message': 'invalid user name or password (6)'}

**Comment by prnzngr** [comment]
https://wiki.mikrotik.com/wiki/Manual:API#Initial_login

**Comment by Poirus9** [comment]
to make it work just change login procedure in api/__init__.py to:
    def login(self, username, password):
        """
        Perform API login

        Args:
            username - Username used to login
            password - Password used to login
        """

        self.talk(["/login",
                   "=name=%s" % username,
                   "=password=%s" % password])

**Comment by prnzngr** [comment]
Thanks. It works!
